### ISSUE TITLE
Problem packaging osx, electron-packager identifier.replace

### ISSUE THREAD

**Issue by itsjimbo** [appelgriebsch/electron-boilerplate#2]
Thank you very much for this, very appreciated!

Got an error when running the following 
```
npm run build:osx 
```

I am not very familiar with electron-packager, so I am not sure if I missed a config option, I did follow your instructions though and "npm start" works fine.  Also tried the latest version (7.0.3) same issue.  

```
> boilerplate@0.9.0 package:osx-app /appelgriebsch-electron-boilerplate-83fc256
> electron-packager app/ $npm_package_productName --arch x64 --platform darwin --app-version $npm_package_version --app-copyright "Copyright (c) 2016 $npm_package_author_name" --app-bundle-id $npm_package_config_id --asar --icon $npm_package_config_png --prune --out build/

Packaging app for platform darwin x64 using electron v1.2.2
/appelgriebsch-electron-boilerplate-83fc256/node_modules/electron-packager/mac.js:32
  return identifier.replace(/ /g, '-').replace(/[^a-zA-Z0-9.-]/g, '')
                    ^

TypeError: identifier.replace is not a function
    at filterCFBundleIdentifier (/appelgriebsch-electron-boilerplate-83fc256/node_modules/electron-packager/mac.js:32:21)
    at buildMacApp (/appelgriebsch-electron-boilerplate-83fc256/node_modules/electron-packager/mac.js:90:33)
    at /appelgriebsch-electron-boilerplate-83fc256/node_modules/electron-packager/common.js:225:7
    at end (/appelgriebsch-electron-boilerplate-83fc256/node_modules/run-series/index.js:8:15)
    at done (/appelgriebsch-electron-boilerplate-83fc256/node_modules/run-series/index.js:11:10)
    at each (/appelgriebsch-electron-boilerplate-83fc256/node_modules/run-series/index.js:16:43)
    at /appelgriebsch-electron-boilerplate-83fc256/node_modules/electron-packager/common.js:62:7
    at next (/appelgriebsch-electron-boilerplate-83fc256/node_modules/rimraf/rimraf.js:74:7)
    at FSReqWrap.CB [as oncomplete] (/appelgriebsch-electron-boilerplate-83fc256/node_modules/rimraf/rimraf.js:110:9)

```

Versions of npm/node/osx below also.
```
~/node -v
v6.2.1
~/npm -v
3.9.3
~/uname -a
Darwin 15.5.0 Darwin Kernel Version 15.5.0: RELEASE_X86_64 x86_64
```

**Comment by appelgriebsch** [comment]
what is the content of your package.json (specially the one in the app/ folder)? the configuration values for the electron-packager are taken from there. could it be that there is a typo or missing setting?

**Comment by appelgriebsch** [comment]
which branch do you use? angular or react?

**Comment by itsjimbo** [comment]
react brach

contents of app/package.json were directly from the source, didn't change much..

```
{
  "name": "boilerplate",
  "productName": "Boilerplate",
  "description": "An Electron boilerplate project (react.js variant)",
  "version": "0.9.0",
  "author": "Andreas Gerlach <andi@appelgriebsch.org>",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/appelgriebsch/electron-boilerplate.git"
  },
  "keywords": [
    "electron",
    "boilerplate",
    "reactjs"
  ],
  "config": {
    "id": "com.appelgriebsch.electron-boilerplate",
    "ico": "assets/boilerplate.ico",
    "icns": "assets/boilerplate.icns",
    "png": "assets/boilerplate.png"
  },
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/appelgriebsch/electron-boilerplate/issues"
  },
  "homepage": "https://github.com/appelgriebsch/electron-boilerplate#readme",
  "dependencies": {
    "electron-debug": "^1.0.0",
    "geopouch": "^2.0.0",
    "history": "^3.0.0",
    "keymirror": "^0.1.1",
    "level": "^1.4.0",
    "leveldown": "^1.4.4",
    "levelgraph": "^1.1.0",
    "levelgraph-jsonld": "^0.5.0",
    "levelgraph-n3": "^1.0.0",
    "levelgraph-query": "^1.0.4",
    "material-ui": "^0.15.0",
    "mime": "^1.3.4",
    "node-servicefinder": "appelgriebsch/node-servicefinder",
    "nuclear-js": "^1.2.1",
    "pouchdb": "^5.1.0",
    "pouchdb-find": "^0.10.0",
    "pouchdb-quick-search": "^1.1.0",
    "radium": "^0.17.1",
    "react": "^15.0.0",
    "react-dom": "^15.1.0",
    "react-router": "^2.0.0",
    "react-tap-event-plugin": "^1.0.0",
    "transform-pouch": "^1.0.2",
    "uuid": "^2.0.1",
    "vis": "^4.16.1"
  }
}

```

**Comment by appelgriebsch** [comment]
OK, found the missing piece. Its the bundle identifier setting for the electron-packager and the setting was missing in the package.json in the project root...

**Comment by itsjimbo** [comment]
Ok thanks! nicely done, sorry I couldn't help more.
I also checked out electron boilerplate from here https://github.com/chentsulin/electron-react-boilerplate
Wanted to know your thoughts on that project as well, AFAIK you have a more comprehensive build cycle in the webpack package.json build options
